### ISSUE TITLE
"Players on Mixed" ignores Observers

### ISSUE THREAD

**Issue by OCNsOMEN** [unixfox/grafana-stratusnetwork#11]
Not sure if it's intended to ignore obs. If it's intended, I think it would be better to call it "Players ingame on Mixed" or "Players playing on Mixed"

It shows 1 player on mixed: https://gyazo.com/09ce693d1f04df6f4f69ec3b5cb665b8
But there are 4 Players on the server: https://gyazo.com/830c4902cd84324d063ea0a10fe355ce

**Comment by unixfox** [comment]
Yes it intended and if you place your mouse on the "I" (left corner of the panel) it's explained.
You are right I'll rename the panel to avoid confusion.
