### ISSUE TITLE
Add sound to signify when match ends

### ISSUE THREAD

**Issue by Palmidence** [unixfox/grafana-stratusnetwork#19]
From the suggestion on the forums, which I agree with (https://stratus.network/forums/posts/5b7e41f0ba159600010045da) - I've sent a link to the game ending sound to @unixfox.

**Comment by unixfox** [comment]
That's a great idea! What do you think: should I enable this feature by default? I'll anyway implement a feature where you can opt out.

**Comment by unixfox** [comment]
It's now implemented and there is a button to disable the sound.

**Comment by unixfox** [comment]
Reopen the issue because the code is not working correctly.

**Comment by unixfox** [comment]
It's now working but on Chrome/Opera/Vivaldi it's a bit special because you need to click anywhere on the website to activate the sound.
