### ISSUE TITLE
Win Predictor fires too often

### ISSUE THREAD

**Issue by Siceth** [unixfox/grafana-stratusnetwork#22]
Because the win predictor pulls stats from the Stratus website and the website doesn't properly remove players ([see this issue](https://github.com/StratusNetwork/issues/issues/213)), the statistics displayed is the result of statting incorrect players as people join and leave the match.

In other words, the maximum accuracy of the utility is when it's ran at the near-beginning of the match (around 30 seconds in) or when upwards of 95% of the original players are still playing.

Potential fixes:
1. Only run the predictor program once either by detecting when to run it or use caching
2. Adjust the predictor program to pull a player list from the bot continuously, rather than from the website

**Comment by unixfox** [comment]
I'm currently trying to get all the players on mixed with my bot for the issue #15 so I think the second choose is better. I'll expose an API so that it will be easier for your program to get the player list.

**Comment by Siceth** [comment]
Implemented successfully! Grafana might have to use some internal caching to reduce strain on my server, but for now, this is effective.
