### ISSUE TITLE
Announce first kill

### ISSUE THREAD

**Issue by Siceth** [unixfox/grafana-stratusnetwork#26]
It's kinda like MVP -- mostly pointless, but it'll give something for people to try for.

**Comment by unixfox** [comment]
Is this a new metrics for the dashboard or for the bot to announce it in the chat at the end of the match?

**Comment by Siceth** [comment]
I would think the bot should announce it as it happens near the beggining of the match.

(And sorry if I picked the wrong labels, still getting used to those!)

**Comment by unixfox** [comment]
Shouldn't it announce it at the end of the match? Because if someone wants to know the first kill at the beginning of the match he just have to scroll up in his chat and it could be considered as spam for mods.
If instead it announce it at the end I can add your idea to this issue: #24.

**Comment by Siceth** [comment]
Oh, duh. I keep forgetting people play with different death message settings. I'm used to not seeing nearly any death messages, so I guess first kill would be doable by scrolling. Ah well.
