### ISSUE TITLE
Time remaining

### ISSUE THREAD

**Issue by unixfox** [unixfox/grafana-stratusnetwork#5]
New metric: the time remaining of the match currently played on mixed

**Comment by unixfox** [comment]
The only way to get this information is from the boss bar but my library doesn't support it so I've to subtract the timelimit with the length of the match only if the timelimit is set by default.

**Comment by Siceth** [comment]
And how do you determine the time limit? Is there a command for that or would you have to scrub XMLs or do some manual associations?

**Comment by unixfox** [comment]
There is a command, it's `/tl` or `/timelimit` in the chat.
